INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (0, 'NO APLICA');
INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (1, 'PRIMER GRADO ASCENDENTE');
INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (2, 'PRIMER GRADO DESCENDENTE');
INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (3, 'SEGUNDO GRADO ASCENDENTE');
INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (4, 'SEGUNDO GRADO COLATERAL');
INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (5, 'SEGUNDO GRADO DESCENDENTE');
INSERT INTO GRADO_CONSANGUINIDAD (GRADO_CONSANGUINIDAD_ID, DESCRIPCION) VALUES (6, 'TERCER GRADO COLATERAL');