Insert into INSTITUCION_PENSIONADO (INSTITUCION_PENSIONADO_ID,DESCRIPCION,ESTADO) values (1,'PENSIONADOS DE LA POLICIA NACIONAL','AC');
Insert into INSTITUCION_PENSIONADO (INSTITUCION_PENSIONADO_ID,DESCRIPCION,ESTADO) values (2,'PENSIONADOS DEL SECTOR SALUD','AC');
Insert into INSTITUCION_PENSIONADO (INSTITUCION_PENSIONADO_ID,DESCRIPCION,ESTADO) values (3,'PENSIONADOS DE LAS FUERZAS ARMADAS','AC');
Insert into INSTITUCION_PENSIONADO (INSTITUCION_PENSIONADO_ID,DESCRIPCION,ESTADO) values (4,'PENSIONADOS Y JUBILADOS DEL ESTADO','AC');