INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, ESTADO) VALUES (1, 'SEGURO DE VEJEZ, DISCAPACIDAD Y SOBREVIVENCIA', 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, ESTADO) VALUES (2, 'SEGURO FAMILIAR DE SALUD', 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, ESTADO) VALUES (3, 'SEGURO DE RIESGOS LABORALES', 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, ESTADO) VALUES (4, 'ATENCION MEDICA POR ACCIDENTE DE TRANSITO', 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, ESTADO) VALUES (5, 'ESTANCIAS INFANTILES','AC');