INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, CODIGO_SEGURO_CONTABLE, SEGURO_PADRE_ID, ESTADO) VALUES (1, 'SEGURO DE VEJEZ, DISCAPACIDAD Y SOBREVIVENCIA', 1, NULL, 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, CODIGO_SEGURO_CONTABLE, SEGURO_PADRE_ID, ESTADO) VALUES (2, 'SEGURO FAMILIAR DE SALUD', 3, NULL, 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, CODIGO_SEGURO_CONTABLE, SEGURO_PADRE_ID, ESTADO) VALUES (3, 'SEGURO DE RIESGOS LABORALES', 2, NULL, 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, CODIGO_SEGURO_CONTABLE, SEGURO_PADRE_ID, ESTADO) VALUES (4, 'ATENCION MEDICA POR ACCIDENTE DE TRANSITO', NULL, 2, 'AC');
INSERT INTO SEGURO (SEGURO_ID, DESCRIPCION, CODIGO_SEGURO_CONTABLE, SEGURO_PADRE_ID, ESTADO) VALUES (5, 'ESTANCIAS INFANTILES', NULL, 2, 'AC');
