INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, TIPO_PERSONA, ESTADO) VALUES (1, 'SERVICIO WEB', 2, 'AC');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, TIPO_PERSONA, ESTADO) VALUES (2, 'CARGA ARCHIVOS SFTP', 2, 'AC');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, TIPO_PERSONA, ESTADO) VALUES (3, 'PORTAL WEB', 1, 'AC');