INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, ESTADO) VALUES (1, 'ADMINISTRADOR', 'AC');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, ESTADO) VALUES (2, 'ANONIMOUS','AC');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, ESTADO) VALUES (3, 'PORTAL WEB', 'AC');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, ESTADO) VALUES (4, 'SERVICIOS WEB', 'AC');
INSERT INTO TIPO_USUARIO (TIPO_USUARIO_ID, DESCRIPCION, ESTADO) VALUES (5, 'PORTAL Y SERVICIOS WEB', 'AC');