/**
 * ANTE CUALQUIER AJUSTE A ESTA TABLA, POR FAVOR INCLUIR EN PLAN DE IMPLEMENTACION EL SCRIPT:
 *
 * GRANT SELECT ON CIUDADANO TO SIGMAREP;
 * CREATE OR REPLACE SYNONYM SIGMAREP.CIUDADANO FOR CIUDADANO;
 */
CREATE TABLE CIUDADANO
(
  CIUDADANO_ID                  NUMBER(10)   NOT NULL,
  TIPO_IDENTIFICACION_ID        NUMBER(3) 	 NOT NULL,
  CEDULA                        VARCHAR2(11),
  NSS                           NUMBER(9)    NOT NULL,
  NOMBRE                        VARCHAR2(50) NOT NULL,
  PRIMER_APELLIDO               VARCHAR2(40) NOT NULL,
  SEGUNDO_APELLIDO              VARCHAR2(40),
  MUNICIPIO_ACTA                VARCHAR2(4),
  OFICIALIA_ACTA                NUMBER(4),
  LIBRO_ACTA                    VARCHAR2(10),
  FOLIO_ACTA                    VARCHAR2(10),
  NUMERO_ACTA                   VARCHAR2(10),
  ANIO_ACTA                     NUMBER(4),
  LITERAL_ACTA                  VARCHAR2(20),
  TIPO_LIBRO_ACTA               VARCHAR2(20),
  MUNICIPIO_ID                  NUMBER(4),
  NACIONALIDAD_ID               NUMBER(3),
  EXTRANJERO                    NUMBER(1)    DEFAULT 0 NOT NULL,
  MOTIVO_CANCELACION_ID         NUMBER(3),
  ENTIDAD_NOT_FALLECIMIENTO_ID  NUMBER(5),
  FECHA_NOT_FALLECIMIENTO       DATE,
  FECHA_ACTU_ENTIDAD_PROVEEDORA DATE         NOT NULL,
  FECHA_NACIMIENTO              DATE         NOT NULL,
  GENERO                        VARCHAR2(1)  NOT NULL,
  FECHA_DEFUNCION               DATE         NULL,
  FECHA_RECEP_CIU_FALLECIDO		DATE,
  FECHA_ULTIMO_CAMBIO           DATE         NOT NULL,
  ESTADO                        VARCHAR2(2)  NOT NULL,
  FECHA_CANCELACION_JCE         DATE,
  FECHA_CANCELACION_TSS         DATE,
  FECHA_CREACION                DATE
)
;

COMMENT ON TABLE CIUDADANO IS 'Repositorio que almacena los ciudadanos asociados al sistema.';

COMMENT ON COLUMN CIUDADANO.CIUDADANO_ID  IS 'Codigo que identifica el ciudadano';
COMMENT ON COLUMN CIUDADANO.CEDULA  IS 'Codula del ciudadano';
COMMENT ON COLUMN CIUDADANO.TIPO_IDENTIFICACION_ID IS 'ID de Tipo de identificacion segon el catologo';
COMMENT ON COLUMN CIUDADANO.NSS  IS 'Nomero de Segurida Social del ciudadano';
COMMENT ON COLUMN CIUDADANO.NOMBRE  IS 'Nombre del ciudadano';
COMMENT ON COLUMN CIUDADANO.PRIMER_APELLIDO  IS 'Primer Apellido del Ciudadano';
COMMENT ON COLUMN CIUDADANO.SEGUNDO_APELLIDO  IS 'Segundo Apellido del Ciudadano';
COMMENT ON COLUMN CIUDADANO.MUNICIPIO_ACTA IS 'Municipio del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.OFICIALIA_ACTA IS 'Oficialoa del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.LIBRO_ACTA IS 'Libro del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.FOLIO_ACTA IS 'Folio del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.NUMERO_ACTA IS 'Nomero del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.ANIO_ACTA IS 'Aoo del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.LITERAL_ACTA IS 'Literal del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.TIPO_LIBRO_ACTA IS 'Tipo Libro del acta de nacimiento';
COMMENT ON COLUMN CIUDADANO.MUNICIPIO_ID  IS 'Codigo con el que se identifica el municipio del ciudadano';
COMMENT ON COLUMN CIUDADANO.NACIONALIDAD_ID  IS 'Codigo que identifica la nacionalidad del ciudadano';
COMMENT ON COLUMN CIUDADANO.EXTRANJERO IS 'Indica si el ciudadano tiene una codula que cumple con el formato establecido para ciudadanos extranjeros o no. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN CIUDADANO.MOTIVO_CANCELACION_ID IS 'Codigo con el que se identifica el motivo de causa desde la TSS';
COMMENT ON COLUMN CIUDADANO.ENTIDAD_NOT_FALLECIMIENTO_ID IS 'Codigo que identifica la Entidad en el sistema';
COMMENT ON COLUMN CIUDADANO.FECHA_NOT_FALLECIMIENTO IS 'Fecha en la que se notifico el fallecimiento del ciudadano por medio de una novedad.';
COMMENT ON COLUMN CIUDADANO.FECHA_ACTU_ENTIDAD_PROVEEDORA IS 'Fecha de actualizacion del registro del ciudadano';
COMMENT ON COLUMN CIUDADANO.FECHA_NACIMIENTO  IS 'Fecha de nacimiento del ciudadano';
COMMENT ON COLUMN CIUDADANO.GENERO  IS 'Gonero del Ciudadano. Posibles valores: M = Masculino, F = Femenino';
COMMENT ON COLUMN CIUDADANO.FECHA_DEFUNCION  IS 'Fecha de defuncion del ciudadano';
COMMENT ON COLUMN CIUDADANO.FECHA_RECEP_CIU_FALLECIDO IS 'Fecha en la que fue recibido el ciudadano cancelado por fallecimiento desde la TSS';
COMMENT ON COLUMN CIUDADANO.FECHA_ULTIMO_CAMBIO IS 'Fecha en la que se realizo el oltimo cambio en el registro.';
COMMENT ON COLUMN CIUDADANO.ESTADO IS 'Estado del ciudadano. Posibles valores: AC = Activo, IN = Inactivo';
COMMENT ON COLUMN CIUDADANO.FECHA_CANCELACION_JCE IS 'Fecha de cancelacion del ciudadano en la JCE';
COMMENT ON COLUMN CIUDADANO.FECHA_CANCELACION_TSS IS 'Fecha de cancelacion del ciudadano en la TSS';

CREATE UNIQUE INDEX CIUDADANO_IDX ON CIUDADANO(CIUDADANO_ID) ;
CREATE UNIQUE INDEX CIUDADANO_NSS_IDX ON CIUDADANO(NSS) ;
CREATE INDEX CIUDADANO_CEDULA_IDX ON CIUDADANO(CEDULA) ;
CREATE INDEX CIUDADANO_MUNICIPIO_IDX ON CIUDADANO(MUNICIPIO_ID) ;
CREATE INDEX CIUDADANO_NACIONALIDAD_IDX ON CIUDADANO(NACIONALIDAD_ID) ;
CREATE INDEX CIUDADANO_ACTA_NACIMIENTO_IDX ON CIUDADANO(MUNICIPIO_ACTA, OFICIALIA_ACTA, LIBRO_ACTA, FOLIO_ACTA, NUMERO_ACTA, ANIO_ACTA, LITERAL_ACTA, TIPO_LIBRO_ACTA) ;
CREATE INDEX CIUDADANO_MOTIVO_CANC_IDX ON CIUDADANO(MOTIVO_CANCELACION_ID) ;
CREATE INDEX CIUDADANO_FEC_NOT_FALLEC_IDX ON CIUDADANO(FECHA_NOT_FALLECIMIENTO) ;
CREATE INDEX CIUDADANO_FEC_ULTIMO_CMB_IDX ON CIUDADANO(FECHA_ULTIMO_CAMBIO) ;


ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_PK PRIMARY KEY (CIUDADANO_ID) USING INDEX CIUDADANO_IDX;
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_MUNICIPIO_FK FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIO(MUNICIPIO_ID);
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_NACIONALIDAD_FK FOREIGN KEY (NACIONALIDAD_ID) REFERENCES NACIONALIDAD(NACIONALIDAD_ID);
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_EXTRANJERO_CK CHECK (EXTRANJERO IN (0, 1));
ALTER TABLE CIUDADANO ADD CONSTRAINT CIU_MOTIVO_CANC_CIUDADANO_FK FOREIGN KEY (MOTIVO_CANCELACION_ID) REFERENCES MOTIVO_CANCELACION_CIUDADANO(MOTIVO_CANCELACION_ID);
ALTER TABLE CIUDADANO ADD CONSTRAINT CIU_ENT_NOT_FALLECIMIENTO_FK FOREIGN KEY (ENTIDAD_NOT_FALLECIMIENTO_ID) REFERENCES ENTIDAD(ENTIDAD_ID);
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_GENERO_CK CHECK (GENERO IN ('F', 'M'));
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_ESTADO_CK CHECK (ESTADO IN ('AC', 'IN'));
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_CEDULA_UK UNIQUE(CEDULA);
ALTER TABLE CIUDADANO ADD CONSTRAINT CIUDADANO_NSS_UK UNIQUE(NSS);
