CREATE TABLE ENTIDAD
(
  ENTIDAD_ID                   	NUMBER(5)     NOT NULL,
  TIPO_ENTIDAD_ID              	NUMBER(3)     NOT NULL,
  CLAVE_ENTIDAD                	NUMBER(4)     NOT NULL,
  SIGLA                        	VARCHAR2(10),
  DESCRIPCION                  	VARCHAR2(150) NOT NULL,
  REGIMEN_ID                   	NUMBER(2),
  PARTICIPA_AFILIACION_AUT     	NUMBER(1)     NOT NULL,
  RNC                          	VARCHAR2(9),
  ENTIDAD_SUPERVISORA_ID       	NUMBER(5),
  ESTADO                       	VARCHAR2(2)   NOT NULL,
  MUNICIPIO_ID                 	NUMBER(4),
  GRUPO_ECONOMICO_ID           	NUMBER(3),
  FECHA_INSCRIPCION  		    DATE
)
TABLESPACE SIGMA_DATA;

COMMENT ON TABLE ENTIDAD IS 'Catalogo de Entidades asociadas al Sistema';

COMMENT ON COLUMN ENTIDAD.ENTIDAD_ID IS 'Codigo que identifica la Entidad en el sistema';
COMMENT ON COLUMN ENTIDAD.TIPO_ENTIDAD_ID IS 'Codigo que identifica el Tipo de Entidad a la que pertenece la entidad';
COMMENT ON COLUMN ENTIDAD.CLAVE_ENTIDAD IS 'Codigo que identifica la Entidad en el SDSS';
COMMENT ON COLUMN ENTIDAD.SIGLA IS 'Siglas de la Entidad';
COMMENT ON COLUMN ENTIDAD.DESCRIPCION IS 'Descripcion de la Entidad';
COMMENT ON COLUMN ENTIDAD.REGIMEN_ID IS 'Codigo del regimen';
COMMENT ON COLUMN ENTIDAD.PARTICIPA_AFILIACION_AUT IS 'Indicador que determina si la entidad participa en el proceso de afiliacion automatica. Posibles valores: 0 = No, 1 = Si';
COMMENT ON COLUMN ENTIDAD.RNC IS 'RNC que identifica la entidad';
COMMENT ON COLUMN ENTIDAD.ENTIDAD_SUPERVISORA_ID IS 'Codigo que identifica la Entidad supervisora en el sistema';
COMMENT ON COLUMN ENTIDAD.ESTADO IS 'Estado de la Entidad. Posibles valores: AC = Activo, IN = Inactivo';
COMMENT ON COLUMN ENTIDAD.LDAP_ORGANIZATION_UNIT IS 'Codigo que identifica la rama a la que pertenece la entidad en LDAP';
COMMENT ON COLUMN ENTIDAD.USUARIO_ARCHIVO IS 'Codigo del usuario autorizado para cargar el archivo en las entidades';
COMMENT ON COLUMN ENTIDAD.TIPO_FONDO_ID IS 'Codigo que identifica el tipo de fondo';
COMMENT ON COLUMN ENTIDAD.TIPO_EMPLEADOR_ID IS 'Codigo que identifica el tipo de empleador';
COMMENT ON COLUMN ENTIDAD.TIPO_ADMINISTRACION_ID IS 'Codigo que identifica el tipo de administracion';
COMMENT ON COLUMN ENTIDAD.TIPO_ESTANCIA_INFANTIL_ID IS 'Codigo que identifica el tipo de estancia infantil';
COMMENT ON COLUMN ENTIDAD.MUNICIPIO_ID IS 'Codigo con el que se identifica el municipio en el catalogo de municipio';
COMMENT ON COLUMN ENTIDAD.GRUPO_ECONOMICO_ID IS 'Codigo que identifica el grupo economico';
COMMENT ON COLUMN ENTIDAD.COMPARTE_CONTACTOS_GRUPO_ECO IS 'Indicador que determina si la entidad comparte contactos con otras entidades del mismo grupo economico. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN ENTIDAD.COMPARTE_AGENTES_GRUPO_ECO IS 'Indicador que determina si la entidad comparte agentes promotores y representantes con otras entidades del mismo grupo economico. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN ENTIDAD.CODIGO_CLIENTE_FACTURACION IS 'Codigo de Cliente para la facturacion de servicio';
COMMENT ON COLUMN ENTIDAD.ACCIONISTA IS 'Indicador que determina si la entidad es accionista. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN ENTIDAD.APLICA_MEMBRESIA IS 'Indicador que determina si la entidad aplica para la facturacion por membresia. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN ENTIDAD.APLICA_FACTURACION IS 'Indicador que determina la entidad aplica para facturacion de servicios. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN ENTIDAD.VALIDA_EDAD_IND_SEGURO_VIDA IS 'Indicador que determina si se realiza la validacion de la edad maxima para la individualizacion del Seguro de Vida para la entidad. Aplicable a entidades administradoras en el Seguro de Pensiones. Posibles valores 0=No, 1=Si';
COMMENT ON COLUMN ENTIDAD.FECHA_INSCRIPCION IS 'Fecha de inscripcion de la entidad';
COMMENT ON COLUMN ENTIDAD.NUMERO_ACREDITACION IS 'Numero de acreditacion otorgado por la entidad supervisora';
COMMENT ON COLUMN ENTIDAD.VALIDA_EDAD_IND_SEGURO_VIDA IS 'Indicador que determina si se realiza la validacion de la antiguedad maxima para la individualizacion del Seguro de Vida para la entidad. Aplicable a entidades administradoras en el Seguro de Pensiones. Posibles valores 0=No, 1=Si';

CREATE UNIQUE INDEX ENTIDAD_IDX ON ENTIDAD(ENTIDAD_ID) TABLESPACE SIGMA_INDEX;
CREATE INDEX ENTIDAD_TIPO_ENTIDAD_IDX ON ENTIDAD(TIPO_ENTIDAD_ID) TABLESPACE SIGMA_INDEX;
CREATE INDEX ENTIDAD_REGIMEN_IDX ON ENTIDAD(REGIMEN_ID) TABLESPACE SIGMA_INDEX;

ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_PK PRIMARY KEY (ENTIDAD_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_TIPO_ENTIDAD_FK FOREIGN KEY (TIPO_ENTIDAD_ID) REFERENCES TIPO_ENTIDAD(TIPO_ENTIDAD_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_REGIMEN_FK FOREIGN KEY (REGIMEN_ID) REFERENCES REGIMEN(REGIMEN_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_PARTICIPA_AFI_AUT_CK CHECK (PARTICIPA_AFILIACION_AUT in (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_ENTIDAD_FK FOREIGN KEY (ENTIDAD_SUPERVISORA_ID) REFERENCES ENTIDAD(ENTIDAD_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ESTADO_ENTIDAD_CK CHECK (ESTADO in ('AC', 'IN'));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_TIPO_FONDO_FK FOREIGN KEY (TIPO_FONDO_ID) REFERENCES TIPO_FONDO(TIPO_FONDO_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_TIPO_EMPLEADOR_FK FOREIGN KEY (TIPO_EMPLEADOR_ID) REFERENCES TIPO_EMPLEADOR(TIPO_EMPLEADOR_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_TIPO_ADMINISTRACION_FK FOREIGN KEY (TIPO_ADMINISTRACION_ID) REFERENCES TIPO_ADMINISTRACION(TIPO_ADMINISTRACION_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_TIP_ESTANCIA_INFANTIL_FK FOREIGN KEY (TIPO_ESTANCIA_INFANTIL_ID) REFERENCES TIPO_ESTANCIA_INFANTIL(TIPO_ESTANCIA_INFANTIL_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_MUNICIPIO_FK FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIO(MUNICIPIO_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_GRUPO_ECONOMICO_FK FOREIGN KEY (GRUPO_ECONOMICO_ID) REFERENCES GRUPO_ECONOMICO(GRUPO_ECONOMICO_ID);
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_COMPARTE_CTO_GRP_ECO_CK CHECK (COMPARTE_CONTACTOS_GRUPO_ECO IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_COMPARTE_AGENTE_GRP_ECO_CK CHECK (COMPARTE_AGENTES_GRUPO_ECO IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_ACCIONISTA_CK CHECK (ACCIONISTA IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_APLICA_MEMBRESIA_CK CHECK (APLICA_MEMBRESIA IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENTIDAD_APLICA_FACTURACION_CK CHECK (APLICA_FACTURACION IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_REQ_APROB_APLIC_BAJA_CK CHECK (REQ_APROBACION_APLIC_BAJA_AU IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT VALIDA_EDAD_IND_SVA_CK CHECK (VALIDA_EDAD_IND_SEGURO_VIDA IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_APLICA_PART_MOV_FONDO_CK CHECK (APLICA_PART_MOVIMIENTO_FONDO IN (0, 1));
ALTER TABLE ENTIDAD ADD CONSTRAINT ENT_VAL_ANTG_IND_SEG_VIDA_CK CHECK (VALIDA_ANTG_IND_SEGURO_VIDA IN (0, 1));