CREATE TABLE INSTITUCION_PENSIONADO
(
  INSTITUCION_PENSIONADO_ID    NUMBER(3)     NOT NULL,
  DESCRIPCION                  VARCHAR2(200) NOT NULL,
  ESTADO                       VARCHAR2(2)   NOT NULL
)
;

COMMENT ON TABLE INSTITUCION_PENSIONADO IS 'Repositorio que almacena las instituciones de pensionados.';

COMMENT ON COLUMN INSTITUCION_PENSIONADO.INSTITUCION_PENSIONADO_ID IS 'Código único que identifica la institución de pensionado';
COMMENT ON COLUMN INSTITUCION_PENSIONADO.DESCRIPCION IS 'Descripción de la institución de pensionado';
COMMENT ON COLUMN INSTITUCION_PENSIONADO.ESTADO IS 'Estado de la Institución de Pensionado. Posibles valores: AC = Activo, IN = Inactivo';

CREATE UNIQUE INDEX INSTITUCION_PENSIONADO_IDX ON INSTITUCION_PENSIONADO(INSTITUCION_PENSIONADO_ID) ;

ALTER TABLE INSTITUCION_PENSIONADO ADD CONSTRAINT INSTITUCION_PENSIONADO_PK PRIMARY KEY (INSTITUCION_PENSIONADO_ID) USING INDEX INSTITUCION_PENSIONADO_IDX;
ALTER TABLE INSTITUCION_PENSIONADO ADD CONSTRAINT INSTITUCION_PENSIONADO_ST_CK CHECK (ESTADO IN ('AC', 'IN'));