CREATE TABLE MUNICIPIO
(
  MUNICIPIO_ID     NUMBER(4)     NOT NULL,
  DESCRIPCION      VARCHAR2(150) NOT NULL,
  CODIGO_MUNICIPIO VARCHAR2(4)   NOT NULL,
  PROVINCIA_ID     NUMBER(3)     NOT NULL,
  ESTADO           VARCHAR2(2)   NOT NULL
)
;

COMMENT ON TABLE MUNICIPIO IS 'Repositorio que aloja los municipios en los que estan divididas las localidades de salud';

COMMENT ON COLUMN MUNICIPIO.MUNICIPIO_ID IS 'Codigo con el que se identifica el municipio en el catalogo de municipio';
COMMENT ON COLUMN MUNICIPIO.DESCRIPCION IS 'Nombre del municipio registrado';
COMMENT ON COLUMN MUNICIPIO.CODIGO_MUNICIPIO IS 'Codigo conocido por el negocio con el que se registra el municipio en el catalogo de municipio';
COMMENT ON COLUMN MUNICIPIO.PROVINCIA_ID IS 'Codigo con el que se identifica la provincia en el catalogo de provincias';
COMMENT ON COLUMN MUNICIPIO.ESTADO IS 'Estado del municipio. Posibles valores: AC = Activo, IN = Inactivo';

CREATE UNIQUE INDEX MUNICIPIO_IDX ON MUNICIPIO(MUNICIPIO_ID) ;

ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY (MUNICIPIO_ID);
ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_CODIGO_MUNICIPIO_UK UNIQUE(CODIGO_MUNICIPIO);
ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_PROVINCIA_FK FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIA(PROVINCIA_ID);
ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_ESTADO_CK CHECK (ESTADO in ('AC', 'IN'));
