CREATE TABLE USUARIO
(
  USUARIO_ID                    NUMBER(5)     NOT NULL,
  CODIGO                        VARCHAR2(30)  NOT NULL,
  CONTACTO_ID                   NUMBER(6)     NOT NULL,
  TIPO_USUARIO_ID               NUMBER(3)     NOT NULL,
  USUARIO_ULTIMO_CAMBIO_ID      NUMBER(5),
  LLAVE_ENCRIPTACION_CLAVE      VARCHAR2(150),
  FECHA_ULTIMA_AUTENTICACION    DATE,
  FECHA_ULTIMO_CAMBIO           DATE,
  ESTADO                        VARCHAR2(2)   NOT NULL,
  FECHA_NOTIFICACION_BLOQUEO    DATE
)
TABLESPACE SEG_DATA;

COMMENT ON TABLE USUARIO IS 'Catálogo de usuarios del sistema';

COMMENT ON COLUMN USUARIO.USUARIO_ID IS 'Número secuencial que identifica el usuario';
COMMENT ON COLUMN USUARIO.CODIGO IS 'Código del usuario';
COMMENT ON COLUMN USUARIO.CONTACTO_ID IS 'Código que identifica al contacto asociado al usuario';
COMMENT ON COLUMN USUARIO.TIPO_USUARIO_ID IS 'Código único que identifica el tipo de usuario';
COMMENT ON COLUMN USUARIO.USUARIO_ULTIMO_CAMBIO_ID IS 'ID del usuario que realizo el ultimo cambio del registro';
COMMENT ON COLUMN USUARIO.LLAVE_ENCRIPTACION_CLAVE IS 'Caracteres utlizado para la encriptacion de la clave del usuario';
COMMENT ON COLUMN USUARIO.FECHA_ULTIMA_AUTENTICACION IS 'Fecha de ultima autenticación del usuario';
COMMENT ON COLUMN USUARIO.FECHA_ULTIMO_CAMBIO IS 'Fecha de ultimo cambio del registro.';
COMMENT ON COLUMN USUARIO.CANT_AVISOS_PROX_VENC_CLAVE IS 'Cantidad de avisos del próximo vencimiento de la clave';
COMMENT ON COLUMN USUARIO.FECHA_ULT_AVISO_PROX_VENC_CLV IS 'Fecha de ultimo aviso de próximo vencimiento de la clave';
COMMENT ON COLUMN USUARIO.FECHA_AVISO_VENC_CLV IS 'Fecha de vecimiento de la clave.';
COMMENT ON COLUMN USUARIO.ESTADO IS 'Estado del usuario. Posibles valores: AC = Activo, IN = Inactivo';
COMMENT ON COLUMN USUARIO.FECHA_NOTIFICACION_BLOQUEO IS 'Fecha en que fue realizada la notificación del bloqueo de usuario';

CREATE UNIQUE INDEX USUARIO_IDX ON USUARIO(USUARIO_ID) TABLESPACE SEG_DATA;
CREATE INDEX USUARIO_CODIGO_IDX ON USUARIO(CODIGO) TABLESPACE SEG_DATA;
CREATE INDEX USUARIO_CONTACTO_IDX ON USUARIO(CONTACTO_ID) TABLESPACE SEG_DATA;
CREATE INDEX USUARIO_TIPO_USUARIO_IDX ON USUARIO(TIPO_USUARIO_ID) TABLESPACE SEG_DATA;
CREATE INDEX USUARIO_USUARIO_ULT_CAMB_IDX ON USUARIO(USUARIO_ULTIMO_CAMBIO_ID) TABLESPACE SEG_DATA;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_CODIGO_UK UNIQUE(CODIGO);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_CONTACTO_FK FOREIGN KEY (CONTACTO_ID) REFERENCES CONTACTO(CONTACTO_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_TIPO_USUARIO_FK FOREIGN KEY (TIPO_USUARIO_ID) REFERENCES TIPO_USUARIO(TIPO_USUARIO_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_USUARIO_ULTIMO_FK FOREIGN KEY (USUARIO_ULTIMO_CAMBIO_ID) REFERENCES USUARIO(USUARIO_ID);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_ESTADO_CK CHECK (ESTADO IN ('AC', 'IN'));