CREATE TABLE GRADO_CONSANGUINIDAD
(
  GRADO_CONSANGUINIDAD_ID SERIAL PRIMARY KEY,
  DESCRIPCION             VARCHAR(40) NOT NULL
);

COMMENT ON TABLE GRADO_CONSANGUINIDAD IS 'Catálogo de GRADO_CONSANGUINIDAD del sistema';

COMMENT ON COLUMN GRADO_CONSANGUINIDAD.GRADO_CONSANGUINIDAD_ID  IS 'Código que identifica el grado de consanguinidad';
COMMENT ON COLUMN GRADO_CONSANGUINIDAD.DESCRIPCION  IS 'Descripción del grado de consanguinidad';