CREATE TABLE imaged_stored (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	creation_date timestamp NULL,
	file_download_uri varchar(255) NULL,
	file_type varchar(255) NULL,
	file_view_uri varchar(255) NULL,
	"name" varchar(255) NULL,
	"size" int8 NOT NULL,
	update_date timestamp NULL,
	CONSTRAINT imaged_stored_pkey PRIMARY KEY (id)
);