CREATE TABLE PARENTESCO
(
  PARENTESCO_ID                	    SERIAL PRIMARY KEY,
  DESCRIPCION                  		VARCHAR(40) 	NOT NULL,
  TIPO_DEPENDIENTE             		VARCHAR(1) 	NOT NULL,
  GENERO                       		VARCHAR(1),
  GRADO_CONSANGUINIDAD_ID      		INT		NOT NULL,
  ESTADO                       		VARCHAR(2) 	NOT NULL
);

COMMENT ON TABLE PARENTESCO IS 'Catálogo de parentescos del sistema';

COMMENT ON COLUMN PARENTESCO.PARENTESCO_ID IS 'Código que identifica el parentesco';
COMMENT ON COLUMN PARENTESCO.DESCRIPCION IS 'Descripción del parentesco';
COMMENT ON COLUMN PARENTESCO.TIPO_DEPENDIENTE IS 'Tipo de beneficiario. Posibles valores: D = Directo, A = Adicional';
COMMENT ON COLUMN PARENTESCO.GENERO IS 'Género del parentesco. Posibles valores: M = Masculino, F = Femenino';
COMMENT ON COLUMN PARENTESCO.GRADO_CONSANGUINIDAD_ID IS 'Código del grado de consanguinidad entre el titular y dependiente';
COMMENT ON COLUMN PARENTESCO.ESTADO IS 'Estado del parentesco. Posibles valores: AC = Activo, IN = Inactivo';


ALTER TABLE PARENTESCO ADD CONSTRAINT PARENTESCO_GRADO_CONSG_FK FOREIGN KEY (GRADO_CONSANGUINIDAD_ID) REFERENCES GRADO_CONSANGUINIDAD(GRADO_CONSANGUINIDAD_ID);
ALTER TABLE PARENTESCO ADD CONSTRAINT PARENTESCO_TIPO_DEPENDIENTE_CK CHECK (TIPO_DEPENDIENTE IN ('D', 'A'));
ALTER TABLE PARENTESCO ADD CONSTRAINT PARENTESCO_GENERO_CK CHECK (GENERO IN ('M', 'F'));
ALTER TABLE PARENTESCO ADD CONSTRAINT PARENTESCO_ESTADO_CK CHECK (ESTADO IN ('AC', 'IN'));