
CREATE TABLE TIPO_USUARIO
(
  TIPO_USUARIO_ID  SERIAL PRIMARY KEY,
  DESCRIPCION      VARCHAR(150) NOT NULL,
  ESTADO           VARCHAR(2)   NOT NULL
);

COMMENT ON TABLE TIPO_USUARIO IS 'Código único que identifica el tipo de contacto';

COMMENT ON COLUMN TIPO_USUARIO.TIPO_USUARIO_ID IS 'Código único que identifica el tipo de usuario';
COMMENT ON COLUMN TIPO_USUARIO.DESCRIPCION IS 'Descripción del tipo de usuario';
COMMENT ON COLUMN TIPO_USUARIO.ESTADO IS 'Estado del tipo de contacto. Posibles valores: AC = Activo, IN = Inactivo';

ALTER TABLE TIPO_USUARIO ADD CONSTRAINT TIPO_USUARIO_ESTADO_CK CHECK (ESTADO in ('AC', 'IN'));